CREATE USER 
'empresa2026'@'%t' 
IDENTIFIED  BY 'Empresa2026$';


GRANT USAGE ON *.* TO 'empresa2026'@'%';

ALTER USER 'empresa2026'@'%' 
REQUIRE NONE 
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON empresa2026.* 
TO 'empresa2026'@'%';

FLUSH PRIVILEGES;