ALTER TABLE producto
MODIFY id INT NOT NULL AUTO_INCREMENT;


ALTER TABLE cliente
MODIFY id INT NOT NULL AUTO_INCREMENT;


ALTER TABLE pedido
MODIFY id INT NOT NULL AUTO_INCREMENT;


ALTER TABLE lineaspedido
MODIFY id INT NOT NULL AUTO_INCREMENT;

